import type { PangramResponse, WindowData } from '../types/api'

export type Verdict = 'ai' | 'human' | 'mixed'

type AiResultSource = Partial<
  Pick<
    PangramResponse,
    | 'ai_likelihood'
    | 'avg_ai_likelihood'
    | 'fraction_ai_content'
    | 'fraction_ai'
    | 'fraction_human'
    | 'fraction_ai_assisted'
    | 'prediction'
    | 'prediction_short'
    | 'headline'
    | 'provider'
    | 'analysis_mode'
  >
>

const clamp01 = (value: number) => Math.min(1, Math.max(0, value))

const firstProbability = (...values: Array<number | null | undefined>): number | undefined => {
  for (const value of values) {
    if (typeof value === 'number' && Number.isFinite(value)) {
      return clamp01(value)
    }
  }

  return undefined
}

const normalizeText = (value?: string) => (value || '').toLowerCase().trim()

const isLocalSource = (source?: AiResultSource) =>
  source?.provider === 'local' || normalizeText(source?.analysis_mode).startsWith('local')

const localAiProbability = (source?: AiResultSource) =>
  firstProbability(source?.avg_ai_likelihood, source?.ai_likelihood, source?.fraction_ai, source?.fraction_ai_content) ?? 0

const predictionTranslations: Array<{ match: string; ru: string }> = [
  {
    match: 'we believe that this document is a mix of ai-generated, ai-assisted, and human-written content',
    ru: 'Похоже, в документе смешаны ИИ-сгенерированные, ИИ-ассистированные и человеческие фрагменты.',
  },
  {
    match: 'we believe that this document is fully human-written',
    ru: 'Похоже, документ полностью написан человеком.',
  },
  {
    match: 'we believe that this document is fully ai-generated',
    ru: 'Похоже, документ полностью сгенерирован ИИ.',
  },
  {
    match: 'this document appears to be ai-assisted',
    ru: 'Похоже, документ написан человеком с помощью ИИ.',
  },
]

export const localizePredictionText = (value?: string): string => {
  const source = (value || '').trim()
  if (!source) return ''

  const normalized = normalizeText(source)

  const headlineTranslations: Record<string, string> = {
    'highly likely ai': 'Высокая вероятность модельного следа ИИ',
    'likely ai': 'Вероятен модельный след ИИ',
    'unlikely ai': 'Модельный след ИИ маловероятен',
    'mostly human, ai detected': 'В основном человек, обнаружен ИИ',
    'human written': 'Написано человеком',
    'human-written': 'Написано человеком',
    human: 'Написано человеком',
    'ai generated': 'Сгенерировано ИИ',
    'ai-generated': 'Сгенерировано ИИ',
    'ai assisted': 'Написано с помощью ИИ',
    'ai-assisted': 'Написано с помощью ИИ',
    'mixed content': 'Смешанный контент',
    mixed: 'Смешанный контент',
  }

  if (headlineTranslations[normalized]) return headlineTranslations[normalized]

  if (
    normalized.includes('primarily human-written') &&
    normalized.includes('ai-generated') &&
    normalized.includes('ai-assisted')
  ) {
    return 'Похоже, документ в основном написан человеком, но найдены ИИ-сгенерированные и ИИ-ассистированные фрагменты.'
  }

  if (normalized.includes('mostly human') && normalized.includes('ai detected')) {
    return 'В основном человек, обнаружен ИИ'
  }

  for (const item of predictionTranslations) {
    if (normalized === item.match) return item.ru
  }

  return source
}

const verdictFromText = (value?: string): Verdict | undefined => {
  const text = normalizeText(value)
  if (!text) return undefined

  const mixedHints = [
    'ai-assisted',
    'ai assisted',
    'mixed',
    'hybrid',
    'partly',
    'partial',
    'assist',
    'частично',
    'смешан',
  ]
  if (mixedHints.some((hint) => text.includes(hint))) return 'mixed'

  const humanHints = [
    'human-written',
    'human',
    'unlikely ai',
    'written by human',
    'человек',
    'написан человеком',
  ]
  if (humanHints.some((hint) => text.includes(hint))) return 'human'

  const aiHints = ['ai-generated', 'ai generated', 'fully ai', 'likely ai', 'generated by ai', 'ии']
  if (aiHints.some((hint) => text.includes(hint))) return 'ai'

  return undefined
}

const verdictFromShort = (value?: string): Verdict | undefined => {
  const normalized = normalizeText(value)
  if (!normalized) return undefined

  if (normalized === 'ai') return 'ai'
  if (normalized === 'human') return 'human'
  if (normalized === 'mixed' || normalized === 'ai-assisted' || normalized === 'ai assisted') {
    return 'mixed'
  }

  return undefined
}

export const resolveVerdict = (source?: AiResultSource): Verdict => {
  if (isLocalSource(source)) {
    const aiLikelihood = localAiProbability(source)
    if (aiLikelihood >= 0.66) return 'ai'
    if (aiLikelihood <= 0.34) return 'human'
    return 'mixed'
  }

  const byShort = verdictFromShort(source?.prediction_short)
  if (byShort) return byShort

  const byHeadline = verdictFromText(source?.headline)
  if (byHeadline) return byHeadline

  const byPrediction = verdictFromText(source?.prediction)
  if (byPrediction) return byPrediction

  const aiLikelihood = firstProbability(source?.fraction_ai_content, source?.fraction_ai, source?.ai_likelihood) ?? 0
  if (aiLikelihood >= 0.66) return 'ai'
  if (aiLikelihood <= 0.25) return 'human'

  return 'mixed'
}

export const resolveAiDistribution = (source?: AiResultSource) => {
  if (isLocalSource(source)) {
    const ai = localAiProbability(source)
    return {
      ai,
      human: clamp01(1 - ai),
      uncertain: 0,
    }
  }

  const ai = firstProbability(source?.fraction_ai_content, source?.fraction_ai, source?.ai_likelihood) ?? 0
  const assisted = firstProbability(source?.fraction_ai_assisted)
  const human = firstProbability(source?.fraction_human)

  if (typeof human === 'number') {
    const uncertainFromBackend = assisted ?? clamp01(1 - ai - human)
    const sum = ai + human + uncertainFromBackend

    if (sum > 1.0001) {
      return {
        ai: ai / sum,
        human: human / sum,
        uncertain: uncertainFromBackend / sum,
      }
    }

    return { ai, human, uncertain: uncertainFromBackend }
  }

  const uncertain = assisted ?? 0
  const inferredHuman = clamp01(1 - ai - uncertain)

  return { ai, human: inferredHuman, uncertain }
}

export const resolveAiPercent = (source?: AiResultSource) => Math.round(resolveAiDistribution(source).ai * 100)

export const resolveSegmentVerdict = (windowItem: WindowData): Verdict => {
  const byPrediction = verdictFromText(windowItem.prediction)
  if (byPrediction) return byPrediction

  const byLabel = verdictFromText(windowItem.label)
  if (byLabel) return byLabel

  const aiLikelihood = firstProbability(windowItem.ai_likelihood) ?? 0
  if (aiLikelihood >= 0.66) return 'ai'
  if (aiLikelihood <= 0.25) return 'human'

  return 'mixed'
}

export const segmentVerdictClass = (windowItem: WindowData): Verdict => resolveSegmentVerdict(windowItem)

export const segmentVerdictLabel = (windowItem: WindowData) => {
  const verdict = resolveSegmentVerdict(windowItem)
  if (verdict === 'ai') return 'ИИ'
  if (verdict === 'human') return 'Человек'

  return 'Смешано'
}

export const segmentVerdictColor = (windowItem: WindowData) => {
  const verdict = resolveSegmentVerdict(windowItem)
  if (verdict === 'ai') return 'var(--ai)'
  if (verdict === 'human') return 'var(--human)'

  return 'var(--mixed)'
}

export const formatRuDate = (value?: string) =>
  value
    ? new Date(value).toLocaleString('ru-RU', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
    : '—'
